/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Regenerate with:  npm run fal:pricing
 * Source: the `endpointBilling` payload on each fal.ai model page.
 *
 * 916 of 919 models priced (100%).
 * Billing units seen: 1 (2), images (207), units (59), megapixels (225), seconds (163), processed megapixels (17), compute seconds (94), 1000 tokens (12), generations (17), 1m tokens (6), videos (66), credits (13), minutes (2), 5 seconds (7), video segments (21),  (4), input seconds (1).
 *
 * `price` is per ONE `unit`, not per run. Converting to a per-run cost needs
 * the run's own context — duration for `seconds`, output size for
 * `megapixels` — which is why that conversion lives in falPricing.ts rather
 * than being baked in here.
 */

export type FalPriceEntry = {
  /** USD per single billing unit. */
  price: number;
  /** images | videos | seconds | megapixels | units | credits | … */
  unit: string;
  /** Resolution surcharges, when the model publishes them. */
  multipliers?: Record<string, number>;
};

export const FAL_PRICING: Record<string, FalPriceEntry> = {
  "alibaba/happy-horse/image-to-video": { price: 0.14, unit: "units" },
  "alibaba/happy-horse/reference-to-video": { price: 0.14, unit: "seconds" },
  "alibaba/happy-horse/text-to-video": { price: 0.14, unit: "seconds" },
  "alibaba/happy-horse/v1.1/image-to-video": { price: 0.14, unit: "seconds" },
  "alibaba/happy-horse/v1.1/reference-to-video": { price: 0.14, unit: "seconds" },
  "alibaba/happy-horse/v1.1/text-to-video": { price: 0.14, unit: "seconds" },
  "alibaba/qwen-image-3/edit": { price: 0.01, unit: "units" },
  "alibaba/qwen-image-3/text-to-image": { price: 0.01, unit: "units" },
  "argil/avatars/text-to-video": { price: 0.0225, unit: "input seconds" },
  "blackforestlabs/flux-3/first-last-frame-to-video": { price: 0.085, unit: "seconds" },
  "blackforestlabs/flux-3/first-last-frame-to-video/draft": { price: 0.03, unit: "seconds" },
  "blackforestlabs/flux-3/image-to-video": { price: 0.085, unit: "seconds" },
  "blackforestlabs/flux-3/image-to-video/draft": { price: 0.03, unit: "seconds" },
  "blackforestlabs/flux-3/keyframes-to-video": { price: 0.085, unit: "seconds" },
  "blackforestlabs/flux-3/keyframes-to-video/draft": { price: 0.03, unit: "seconds" },
  "blackforestlabs/flux-3/text-to-video": { price: 0.085, unit: "seconds" },
  "blackforestlabs/flux-3/text-to-video/draft": { price: 0.03, unit: "seconds" },
  "bria/embed-product": { price: 0.04, unit: "images" },
  "bria/extract-object": { price: 0.02, unit: "images" },
  "bria/fibo-bbq-preview/generate": { price: 0.04, unit: "images" },
  "bria/fibo-edit/add_object_by_text": { price: 0.04, unit: "images" },
  "bria/fibo-edit/blend": { price: 0.04, unit: "images" },
  "bria/fibo-edit/colorize": { price: 0.04, unit: "images" },
  "bria/fibo-edit/edit": { price: 0.04, unit: "images" },
  "bria/fibo-edit/erase_by_text": { price: 0.04, unit: "images" },
  "bria/fibo-edit/relight": { price: 0.04, unit: "images" },
  "bria/fibo-edit/replace_object_by_text": { price: 0.04, unit: "images" },
  "bria/fibo-edit/reseason": { price: 0.04, unit: "images" },
  "bria/fibo-edit/restore": { price: 0.04, unit: "images" },
  "bria/fibo-edit/restyle": { price: 0.04, unit: "images" },
  "bria/fibo-edit/rewrite_text": { price: 0.04, unit: "images" },
  "bria/fibo-edit/sketch_to_colored_image": { price: 0.04, unit: "images" },
  "bria/fibo-lite/generate": { price: 0.036, unit: "images" },
  "bria/fibo/generate": { price: 0.04, unit: "images" },
  "bria/genfill/v2": { price: 0.04, unit: "megapixels" },
  "bria/product-dimensions": { price: 0.04, unit: "images" },
  "bria/replace-background": { price: 0.04, unit: "images" },
  "bria/upscale/creative": { price: 0.04, unit: "images" },
  "bytedance/lynx": { price: 0.6, unit: "seconds" },
  "bytedance/seedance-2.0/fast/image-to-video": { price: 0.0112, unit: "1000 tokens" },
  "bytedance/seedance-2.0/fast/reference-to-video": { price: 0.0112, unit: "1000 tokens" },
  "bytedance/seedance-2.0/fast/text-to-video": { price: 0.0112, unit: "1000 tokens" },
  "bytedance/seedance-2.0/image-to-video": { price: 0.014, unit: "1000 tokens" },
  "bytedance/seedance-2.0/mini/image-to-video": { price: 0.007, unit: "1000 tokens" },
  "bytedance/seedance-2.0/mini/reference-to-video": { price: 0.007, unit: "1000 tokens" },
  "bytedance/seedance-2.0/mini/text-to-video": { price: 0.007, unit: "1000 tokens" },
  "bytedance/seedance-2.0/reference-to-video": { price: 0.014, unit: "1000 tokens" },
  "bytedance/seedance-2.0/text-to-video": { price: 0.014, unit: "1000 tokens" },
  "bytedance/seedance-2.5/image-to-video": { price: 0.0214, unit: "1000 tokens" },
  "bytedance/seedance-2.5/reference-to-video": { price: 0.0214, unit: "1000 tokens" },
  "bytedance/seedance-2.5/text-to-video": { price: 0.0214, unit: "1000 tokens" },
  "bytedance/seedream/v5/lite/edit": { price: 0.035, unit: "images" },
  "bytedance/seedream/v5/lite/text-to-image": { price: 0.035, unit: "images" },
  "bytedance/seedream/v5/pro/edit": { price: 0.0675, unit: "units" },
  "bytedance/seedream/v5/pro/layerize": { price: 0.03375, unit: "images" },
  "bytedance/seedream/v5/pro/text-to-image": { price: 0.0675, unit: "units" },
  "clarityai/crystal-upscaler": { price: 0.016, unit: "megapixels" },
  "fal-ai/ai-avatar/multi": { price: 0.2, unit: "seconds" },
  "fal-ai/ai-avatar/multi-text": { price: 0.2, unit: "seconds" },
  "fal-ai/ai-avatar/single-text": { price: 0.2, unit: "seconds" },
  "fal-ai/amt-interpolation/frame-interpolation": { price: 0, unit: "compute seconds" },
  "fal-ai/aura-flow": { price: 0, unit: "compute seconds" },
  "fal-ai/aura-sr": { price: 0, unit: "compute seconds" },
  "fal-ai/bagel": { price: 0.1, unit: "images" },
  "fal-ai/bagel/edit": { price: 0.1, unit: "images" },
  "fal-ai/ben/v2/image": { price: 0.025, unit: "megapixels" },
  "fal-ai/bernini-r/edit-image": { price: 0.08, unit: "seconds" },
  "fal-ai/bernini-r/reference-to-video": { price: 0.08, unit: "seconds" },
  "fal-ai/bernini-r/text-to-video": { price: 0.08, unit: "seconds" },
  "fal-ai/birefnet": { price: 0, unit: "compute seconds" },
  "fal-ai/birefnet/v2": { price: 0, unit: "compute seconds" },
  "fal-ai/bitdance": { price: 0.01, unit: "units" },
  "fal-ai/boogu-image": { price: 0.04, unit: "megapixels" },
  "fal-ai/boogu-image/edit": { price: 0.04, unit: "megapixels" },
  "fal-ai/bria/background/remove": { price: 0.018, unit: "generations" },
  "fal-ai/bria/background/replace": { price: 0.04, unit: "generations" },
  "fal-ai/bria/eraser": { price: 0.04, unit: "generations" },
  "fal-ai/bria/expand": { price: 0.04, unit: "generations" },
  "fal-ai/bria/genfill": { price: 0.04, unit: "generations" },
  "fal-ai/bria/product-shot": { price: 0.04, unit: "generations" },
  "fal-ai/bria/reimagine": { price: 0.04, unit: "generations" },
  "fal-ai/bria/text-to-image/base": { price: 0.04, unit: "generations" },
  "fal-ai/bria/text-to-image/fast": { price: 0.028, unit: "generations" },
  "fal-ai/bria/text-to-image/hd": { price: 0.04, unit: "generations" },
  "fal-ai/bytedance/omnihuman": { price: 0.14, unit: "seconds" },
  "fal-ai/bytedance/omnihuman/v1.5": { price: 0.16, unit: "seconds" },
  "fal-ai/bytedance/seedance/v1.5/pro/image-to-video": { price: 1.2, unit: "1m tokens" },
  "fal-ai/bytedance/seedance/v1.5/pro/text-to-video": { price: 1.2, unit: "1m tokens" },
  "fal-ai/bytedance/seedance/v1/pro/fast/image-to-video": { price: 1, unit: "1m tokens" },
  "fal-ai/bytedance/seedance/v1/pro/fast/text-to-video": { price: 1, unit: "1m tokens" },
  "fal-ai/bytedance/seedance/v1/pro/image-to-video": { price: 2.5, unit: "1m tokens" },
  "fal-ai/bytedance/seedance/v1/pro/text-to-video": { price: 2.5, unit: "1m tokens" },
  "fal-ai/bytedance/seedream/v4.5/edit": { price: 0.04, unit: "images" },
  "fal-ai/bytedance/seedream/v4.5/text-to-image": { price: 0.04, unit: "images" },
  "fal-ai/bytedance/seedream/v4/edit": { price: 0.03, unit: "images" },
  "fal-ai/bytedance/seedream/v4/text-to-image": { price: 0.03, unit: "images" },
  "fal-ai/cartoonify": { price: 0.1, unit: "images" },
  "fal-ai/cat-vton": { price: 0, unit: "compute seconds" },
  "fal-ai/ccsr": { price: 0, unit: "compute seconds" },
  "fal-ai/chrono-edit": { price: 0.01, unit: "images" },
  "fal-ai/chrono-edit-lora": { price: 0.02, unit: "images" },
  "fal-ai/chrono-edit-lora-gallery/paintbrush": { price: 0, unit: "compute seconds" },
  "fal-ai/chrono-edit-lora-gallery/upscaler": { price: 0.03, unit: "images" },
  "fal-ai/clarity-upscaler": { price: 0.03, unit: "megapixels" },
  "fal-ai/codeformer": { price: 0.0021, unit: "megapixels" },
  "fal-ai/cogvideox-5b": { price: 0.2, unit: "videos" },
  "fal-ai/cogvideox-5b/image-to-video": { price: 0.2, unit: "videos" },
  "fal-ai/cogview4": { price: 0.1, unit: "megapixels" },
  "fal-ai/control-light": { price: 0.03, unit: "megapixels" },
  "fal-ai/cosmos-predict-2.5/distilled/text-to-video": { price: 0.08, unit: "videos" },
  "fal-ai/cosmos-predict-2.5/image-to-video": { price: 0.2, unit: "videos" },
  "fal-ai/cosmos-predict-2.5/text-to-video": { price: 0.2, unit: "videos" },
  "fal-ai/creatify/aurora": { price: 1, unit: "units" },
  "fal-ai/creative-upscaler": { price: 0, unit: "compute seconds" },
  "fal-ai/davinci-magihuman": { price: 0.05, unit: "seconds" },
  "fal-ai/ddcolor": { price: 0.001, unit: "megapixels" },
  "fal-ai/decart/lucy-5b/image-to-video": { price: 0.15, unit: "videos" },
  "fal-ai/docres": { price: 0.025, unit: "megapixels" },
  "fal-ai/docres/dewarp": { price: 0.03, unit: "megapixels" },
  "fal-ai/drct-super-resolution": { price: 0.0045, unit: "megapixels" },
  "fal-ai/dreamomni2/edit": { price: 0.05, unit: "images" },
  "fal-ai/dreamshaper": { price: 0, unit: "compute seconds" },
  "fal-ai/dwpose": { price: 0.0006, unit: "seconds" },
  "fal-ai/emu-3.5-image/edit-image": { price: 0.15, unit: "images" },
  "fal-ai/emu-3.5-image/text-to-image": { price: 0.15, unit: "images" },
  "fal-ai/ernie-image": { price: 0.03, unit: "megapixels" },
  "fal-ai/ernie-image/lora": { price: 0.035, unit: "megapixels" },
  "fal-ai/ernie-image/lora/turbo": { price: 0.015, unit: "megapixels" },
  "fal-ai/ernie-image/turbo": { price: 0.01, unit: "megapixels" },
  "fal-ai/esrgan": { price: 0, unit: "compute seconds" },
  "fal-ai/evf-sam": { price: 0.005, unit: "1" },
  "fal-ai/fashn/tryon/v1.5": { price: 0.075, unit: "generations" },
  "fal-ai/fashn/tryon/v1.6": { price: 0.075, unit: "generations" },
  "fal-ai/fast-animatediff/text-to-video": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-animatediff/turbo/text-to-video": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-fooocus-sdxl/image-to-image": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-lcm-diffusion": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-lcm-diffusion/image-to-image": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-lcm-diffusion/inpainting": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-lightning-sdxl": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-lightning-sdxl/image-to-image": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-lightning-sdxl/inpainting": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-sdxl": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-sdxl-controlnet-canny": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-sdxl-controlnet-canny/image-to-image": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-sdxl-controlnet-canny/inpainting": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-sdxl/image-to-image": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-sdxl/inpainting": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-svd-lcm": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-svd-lcm/text-to-video": { price: 0, unit: "compute seconds" },
  "fal-ai/fast-svd/text-to-video": { price: 0, unit: "compute seconds" },
  "fal-ai/feynobg": { price: 0.001, unit: "generations" },
  "fal-ai/ffmpeg-api/extract-frame": { price: 0.0002, unit: "seconds" },
  "fal-ai/ffmpeg-api/images-to-video": { price: 0, unit: "compute seconds" },
  "fal-ai/film": { price: 0.0013, unit: "seconds" },
  "fal-ai/finegrain-eraser": { price: 0.045, unit: "images" },
  "fal-ai/finegrain-eraser/bbox": { price: 0.045, unit: "images" },
  "fal-ai/finegrain-eraser/mask": { price: 0.045, unit: "images" },
  "fal-ai/firered-image-edit": { price: 0.0325, unit: "megapixels" },
  "fal-ai/firered-image-edit-v1.1": { price: 0.0325, unit: "megapixels" },
  "fal-ai/flashhead": { price: 0.005, unit: "seconds" },
  "fal-ai/florence-2-large/caption-to-phrase-grounding": { price: 0, unit: "compute seconds" },
  "fal-ai/florence-2-large/dense-region-caption": { price: 0, unit: "compute seconds" },
  "fal-ai/florence-2-large/object-detection": { price: 0, unit: "compute seconds" },
  "fal-ai/florence-2-large/ocr-with-region": { price: 0, unit: "compute seconds" },
  "fal-ai/florence-2-large/open-vocabulary-detection": { price: 0, unit: "compute seconds" },
  "fal-ai/florence-2-large/referring-expression-segmentation": { price: 0, unit: "compute seconds" },
  "fal-ai/florence-2-large/region-proposal": { price: 0, unit: "compute seconds" },
  "fal-ai/florence-2-large/region-to-segmentation": { price: 0, unit: "compute seconds" },
  "fal-ai/flowedit": { price: 0, unit: "compute seconds" },
  "fal-ai/flux-1/dev": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux-1/dev/image-to-image": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux-1/dev/redux": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux-1/krea": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux-1/krea/image-to-image": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux-1/krea/redux": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux-1/schnell": { price: 0.003, unit: "megapixels" },
  "fal-ai/flux-1/schnell/redux": { price: 0.003, unit: "megapixels" },
  "fal-ai/flux-1/srpo": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux-1/srpo/image-to-image": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux-2": { price: 0.012, unit: "megapixels" },
  "fal-ai/flux-2-flex": { price: 0.05, unit: "processed megapixels" },
  "fal-ai/flux-2-flex/edit": { price: 0.05, unit: "processed megapixels" },
  "fal-ai/flux-2-lora-gallery/add-background": { price: 0.021, unit: "processed megapixels" },
  "fal-ai/flux-2-lora-gallery/apartment-staging": { price: 0.021, unit: "processed megapixels" },
  "fal-ai/flux-2-lora-gallery/ballpoint-pen-sketch": { price: 0.021, unit: "megapixels" },
  "fal-ai/flux-2-lora-gallery/digital-comic-art": { price: 0.021, unit: "megapixels" },
  "fal-ai/flux-2-lora-gallery/face-to-full-portrait": { price: 0.021, unit: "processed megapixels" },
  "fal-ai/flux-2-lora-gallery/hdr-style": { price: 0.021, unit: "megapixels" },
  "fal-ai/flux-2-lora-gallery/multiple-angles": { price: 0.021, unit: "processed megapixels" },
  "fal-ai/flux-2-lora-gallery/realism": { price: 0.021, unit: "megapixels" },
  "fal-ai/flux-2-lora-gallery/satellite-view-style": { price: 0.021, unit: "megapixels" },
  "fal-ai/flux-2-lora-gallery/sepia-vintage": { price: 0.021, unit: "megapixels" },
  "fal-ai/flux-2-lora-gallery/virtual-tryon": { price: 0.021, unit: "processed megapixels" },
  "fal-ai/flux-2-max": { price: 0.07, unit: "megapixels" },
  "fal-ai/flux-2-max/edit": { price: 0.07, unit: "processed megapixels" },
  "fal-ai/flux-2-pro": { price: 0.03, unit: "processed megapixels" },
  "fal-ai/flux-2-pro/edit": { price: 0.03, unit: "processed megapixels" },
  "fal-ai/flux-2-pro/outpaint": { price: 0.03, unit: "processed megapixels" },
  "fal-ai/flux-2/edit": { price: 0.012, unit: "processed megapixels" },
  "fal-ai/flux-2/flash": { price: 0.005, unit: "megapixels" },
  "fal-ai/flux-2/flash/edit": { price: 0.005, unit: "processed megapixels" },
  "fal-ai/flux-2/klein/4b": { price: 0.005, unit: "megapixels" },
  "fal-ai/flux-2/klein/4b/base": { price: 0.009, unit: "megapixels" },
  "fal-ai/flux-2/klein/4b/base/edit": { price: 0.009, unit: "megapixels" },
  "fal-ai/flux-2/klein/4b/base/edit/lora": { price: 0.016, unit: "megapixels" },
  "fal-ai/flux-2/klein/4b/base/lora": { price: 0.016, unit: "megapixels" },
  "fal-ai/flux-2/klein/4b/edit": { price: 0.01, unit: "megapixels" },
  "fal-ai/flux-2/klein/4b/edit/lora": { price: 0.01, unit: "megapixels" },
  "fal-ai/flux-2/klein/4b/lora": { price: 0.01, unit: "megapixels" },
  "fal-ai/flux-2/klein/9b": { price: 0.006, unit: "megapixels" },
  "fal-ai/flux-2/klein/9b/base": { price: 0.011, unit: "megapixels" },
  "fal-ai/flux-2/klein/9b/base/edit": { price: 0.011, unit: "megapixels" },
  "fal-ai/flux-2/klein/9b/base/edit/lora": { price: 0.02, unit: "megapixels" },
  "fal-ai/flux-2/klein/9b/base/lora": { price: 0.02, unit: "megapixels" },
  "fal-ai/flux-2/klein/9b/edit": { price: 0.011, unit: "megapixels" },
  "fal-ai/flux-2/klein/9b/edit/lora": { price: 0.015, unit: "megapixels" },
  "fal-ai/flux-2/klein/9b/lora": { price: 0.015, unit: "megapixels" },
  "fal-ai/flux-2/klein/realtime": { price: 0.00194, unit: "compute seconds" },
  "fal-ai/flux-2/lora": { price: 0.021, unit: "megapixels" },
  "fal-ai/flux-2/lora/edit": { price: 0.021, unit: "processed megapixels" },
  "fal-ai/flux-2/turbo": { price: 0.008, unit: "megapixels" },
  "fal-ai/flux-2/turbo/edit": { price: 0.008, unit: "processed megapixels" },
  "fal-ai/flux-control-lora-canny": { price: 0.04, unit: "megapixels" },
  "fal-ai/flux-control-lora-canny/image-to-image": { price: 0.04, unit: "megapixels" },
  "fal-ai/flux-control-lora-depth": { price: 0.04, unit: "megapixels" },
  "fal-ai/flux-control-lora-depth/image-to-image": { price: 0.04, unit: "megapixels" },
  "fal-ai/flux-general": { price: 0.075, unit: "megapixels" },
  "fal-ai/flux-general/differential-diffusion": { price: 0, unit: "compute seconds" },
  "fal-ai/flux-general/image-to-image": { price: 0.075, unit: "megapixels" },
  "fal-ai/flux-general/inpainting": { price: 0.075, unit: "megapixels" },
  "fal-ai/flux-general/rf-inversion": { price: 0, unit: "compute seconds" },
  "fal-ai/flux-kontext-lora": { price: 0.035, unit: "megapixels" },
  "fal-ai/flux-kontext-lora/inpaint": { price: 0.035, unit: "megapixels" },
  "fal-ai/flux-kontext-lora/text-to-image": { price: 0.035, unit: "megapixels" },
  "fal-ai/flux-kontext/dev": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux-krea-lora": { price: 0.035, unit: "megapixels" },
  "fal-ai/flux-krea-lora/image-to-image": { price: 0.035, unit: "megapixels" },
  "fal-ai/flux-krea-lora/inpainting": { price: 0.035, unit: "megapixels" },
  "fal-ai/flux-krea-lora/stream": { price: 0.035, unit: "megapixels" },
  "fal-ai/flux-lora": { price: 0.035, unit: "megapixels" },
  "fal-ai/flux-lora-canny": { price: 0.035, unit: "megapixels" },
  "fal-ai/flux-lora-depth": { price: 0.035, unit: "megapixels" },
  "fal-ai/flux-lora-fill": { price: 0.035, unit: "megapixels" },
  "fal-ai/flux-lora/image-to-image": { price: 0.035, unit: "megapixels" },
  "fal-ai/flux-lora/inpainting": { price: 0.035, unit: "megapixels" },
  "fal-ai/flux-lora/stream": { price: 0.035, unit: "megapixels" },
  "fal-ai/flux-pro/kontext": { price: 0.04, unit: "images" },
  "fal-ai/flux-pro/kontext/max": { price: 0.08, unit: "images" },
  "fal-ai/flux-pro/kontext/max/multi": { price: 0.08, unit: "images" },
  "fal-ai/flux-pro/kontext/max/text-to-image": { price: 0.08, unit: "images" },
  "fal-ai/flux-pro/kontext/multi": { price: 0.04, unit: "images" },
  "fal-ai/flux-pro/kontext/text-to-image": { price: 0.04, unit: "images" },
  "fal-ai/flux-pro/v1.1": { price: 0.04, unit: "megapixels" },
  "fal-ai/flux-pro/v1.1-ultra": { price: 0.06, unit: "images" },
  "fal-ai/flux-pro/v1.1-ultra-finetuned": { price: 0.07, unit: "images" },
  "fal-ai/flux-pro/v1.1-ultra/redux": { price: 0.05, unit: "megapixels" },
  "fal-ai/flux-pro/v1.1/redux": { price: 0.05, unit: "megapixels" },
  "fal-ai/flux-pro/v1/erase": { price: 0.004, unit: "megapixels" },
  "fal-ai/flux-pro/v1/fill": { price: 0.05, unit: "megapixels" },
  "fal-ai/flux-pro/v1/fill-finetuned": { price: 0.06, unit: "megapixels" },
  "fal-ai/flux-pro/v1/vto": { price: 0.005, unit: "processed megapixels" },
  "fal-ai/flux-pulid": { price: 0.0333, unit: "megapixels" },
  "fal-ai/flux-subject": { price: 0.04, unit: "megapixels" },
  "fal-ai/flux-vision-upscaler": { price: 0.1, unit: "megapixels" },
  "fal-ai/flux/dev": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux/dev/image-to-image": { price: 0.03, unit: "megapixels" },
  "fal-ai/flux/dev/redux": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux/krea": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux/krea/image-to-image": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux/krea/redux": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux/schnell": { price: 0.003, unit: "megapixels" },
  "fal-ai/flux/schnell/redux": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux/srpo": { price: 0.025, unit: "megapixels" },
  "fal-ai/flux/srpo/image-to-image": { price: 0.025, unit: "megapixels" },
  "fal-ai/fooocus": { price: 0, unit: "compute seconds" },
  "fal-ai/fooocus/image-prompt": { price: 0, unit: "compute seconds" },
  "fal-ai/fooocus/inpaint": { price: 0, unit: "compute seconds" },
  "fal-ai/fooocus/upscale-or-vary": { price: 0, unit: "compute seconds" },
  "fal-ai/framepack": { price: 0.0333, unit: "seconds" },
  "fal-ai/framepack/f1": { price: 0.0333, unit: "seconds" },
  "fal-ai/framepack/flf2v": { price: 0.0333, unit: "seconds" },
  "fal-ai/gemini-25-flash-image": { price: 0.0398, unit: "images" },
  "fal-ai/gemini-25-flash-image/edit": { price: 0.0398, unit: "images" },
  "fal-ai/gemini-3-pro-image-preview": { price: 0.15, unit: "images" },
  "fal-ai/gemini-3-pro-image-preview/edit": { price: 0.15, unit: "images" },
  "fal-ai/gemini-3.1-flash-image-preview": { price: 0.08, unit: "images", multipliers: {"2K":1.5,"4K":2} },
  "fal-ai/gemini-3.1-flash-image-preview/edit": { price: 0.08, unit: "images", multipliers: {"2K":1.5,"4K":2} },
  "fal-ai/ghiblify": { price: 0.05, unit: "images" },
  "fal-ai/glm-image": { price: 0.05, unit: "megapixels" },
  "fal-ai/glm-image/image-to-image": { price: 0.05, unit: "megapixels" },
  "fal-ai/gpt-image-1-mini": { price: 1, unit: "credits" },
  "fal-ai/gpt-image-1-mini/edit": { price: 1, unit: "credits" },
  "fal-ai/gpt-image-1.5": { price: 1, unit: "units" },
  "fal-ai/gpt-image-1.5/edit": { price: 1, unit: "units" },
  "fal-ai/gpt-image-1/edit-image": { price: 1, unit: "credits" },
  "fal-ai/gpt-image-1/text-to-image": { price: 1, unit: "credits" },
  "fal-ai/heygen/avatar3/digital-twin": { price: 0.034, unit: "seconds" },
  "fal-ai/heygen/avatar4/digital-twin": { price: 0.1, unit: "seconds" },
  "fal-ai/heygen/avatar4/image-to-video": { price: 0.1, unit: "seconds" },
  "fal-ai/heygen/avatar5/digital-twin": { price: 0.1, unit: "seconds" },
  "fal-ai/heygen/v2/video-agent": { price: 0.034, unit: "seconds" },
  "fal-ai/heygen/v3/video-agent": { price: 0.034, unit: "seconds" },
  "fal-ai/hidream-i1-dev": { price: 0.03, unit: "megapixels" },
  "fal-ai/hidream-i1-fast": { price: 0.01, unit: "megapixels" },
  "fal-ai/hidream-i1-full": { price: 0.05, unit: "megapixels" },
  "fal-ai/hidream-i1-full/image-to-image": { price: 0.05, unit: "megapixels" },
  "fal-ai/hidream-o1-image": { price: 0.01, unit: "megapixels" },
  "fal-ai/hidream-o1-image/dev": { price: 0.005, unit: "megapixels" },
  "fal-ai/hidream-o1-image/dev/edit": { price: 0.005, unit: "megapixels" },
  "fal-ai/hidream-o1-image/edit": { price: 0.01, unit: "megapixels" },
  "fal-ai/hunyuan_world": { price: 0.15, unit: "images" },
  "fal-ai/hunyuan-image/v2.1/text-to-image": { price: 0.1, unit: "megapixels" },
  "fal-ai/hunyuan-image/v3/instruct/edit": { price: 0.09, unit: "megapixels" },
  "fal-ai/hunyuan-image/v3/instruct/text-to-image": { price: 0.09, unit: "megapixels" },
  "fal-ai/hunyuan-image/v3/text-to-image": { price: 0.1, unit: "megapixels" },
  "fal-ai/hunyuan-video": { price: 0.4, unit: "videos" },
  "fal-ai/hunyuan-video-image-to-video": { price: 0.4, unit: "videos" },
  "fal-ai/hunyuan-video-v1.5/image-to-video": { price: 0.075, unit: "seconds" },
  "fal-ai/hunyuan-video-v1.5/text-to-video": { price: 0.075, unit: "seconds" },
  "fal-ai/hy-wu-edit": { price: 0.1, unit: "units" },
  "fal-ai/iclight-v2": { price: 0.1, unit: "megapixels" },
  "fal-ai/ideogram/character": { price: 0.05, unit: "images" },
  "fal-ai/ideogram/character/edit": { price: 0.05, unit: "images" },
  "fal-ai/ideogram/character/remix": { price: 0.05, unit: "images" },
  "fal-ai/ideogram/custom-models/generate": { price: 0.03, unit: "images" },
  "fal-ai/ideogram/object-removal": { price: 0.03, unit: "images" },
  "fal-ai/ideogram/remove-background": { price: 0.01, unit: "images" },
  "fal-ai/ideogram/upscale": { price: 0.06, unit: "images" },
  "fal-ai/ideogram/v2": { price: 0.08, unit: "images" },
  "fal-ai/ideogram/v2/edit": { price: 0.08, unit: "images" },
  "fal-ai/ideogram/v2/remix": { price: 0.08, unit: "images" },
  "fal-ai/ideogram/v2/turbo": { price: 0.05, unit: "images" },
  "fal-ai/ideogram/v2/turbo/edit": { price: 0.05, unit: "images" },
  "fal-ai/ideogram/v2/turbo/remix": { price: 0.05, unit: "images" },
  "fal-ai/ideogram/v2a": { price: 0.04, unit: "images" },
  "fal-ai/ideogram/v2a/remix": { price: 0.04, unit: "images" },
  "fal-ai/ideogram/v2a/turbo": { price: 0.025, unit: "images" },
  "fal-ai/ideogram/v2a/turbo/remix": { price: 0.025, unit: "images" },
  "fal-ai/ideogram/v3": { price: 0.03, unit: "images" },
  "fal-ai/ideogram/v3/edit": { price: 0.03, unit: "images" },
  "fal-ai/ideogram/v3/generate-transparent": { price: 0.03, unit: "images" },
  "fal-ai/ideogram/v3/layerize-text": { price: 0.09, unit: "images" },
  "fal-ai/ideogram/v3/reframe": { price: 0.03, unit: "images" },
  "fal-ai/ideogram/v3/remix": { price: 0.03, unit: "images" },
  "fal-ai/ideogram/v3/replace-background": { price: 0.03, unit: "images" },
  "fal-ai/illusion-diffusion": { price: 0, unit: "compute seconds" },
  "fal-ai/image-apps-v2/age-modify": { price: 0.04, unit: "images" },
  "fal-ai/image-apps-v2/city-teleport": { price: 0.04, unit: "images" },
  "fal-ai/image-apps-v2/expression-change": { price: 0.04, unit: "images" },
  "fal-ai/image-apps-v2/hair-change": { price: 0.04, unit: "images" },
  "fal-ai/image-apps-v2/headshot-photo": { price: 0.04, unit: "images" },
  "fal-ai/image-apps-v2/makeup-application": { price: 0.04, unit: "images" },
  "fal-ai/image-apps-v2/object-removal": { price: 0.04, unit: "images" },
  "fal-ai/image-apps-v2/outpaint": { price: 0.035, unit: "megapixels" },
  "fal-ai/image-apps-v2/perspective": { price: 0.04, unit: "images" },
  "fal-ai/image-apps-v2/photo-restoration": { price: 0.04, unit: "images" },
  "fal-ai/image-apps-v2/photography-effects": { price: 0.4, unit: "images" },
  "fal-ai/image-apps-v2/portrait-enhance": { price: 0.4, unit: "images" },
  "fal-ai/image-apps-v2/product-holding": { price: 0.04, unit: "images" },
  "fal-ai/image-apps-v2/product-photography": { price: 0.04, unit: "images" },
  "fal-ai/image-apps-v2/relighting": { price: 0.04, unit: "images" },
  "fal-ai/image-apps-v2/style-transfer": { price: 0.04, unit: "images" },
  "fal-ai/image-apps-v2/texture-transform": { price: 0.04, unit: "images" },
  "fal-ai/image-apps-v2/virtual-try-on": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/age-progression": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/baby-version": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/background-change": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/broccoli-haircut": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/cartoonify": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/color-correction": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/expression-change": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/face-enhancement": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/hair-change": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/object-removal": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/photo-restoration": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/plushie-style": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/professional-photo": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/realism": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/reframe": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/retouch": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/scene-composition": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/style-transfer": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/text-removal": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/time-of-day": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/weather-effect": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/wojak-style": { price: 0.04, unit: "images" },
  "fal-ai/image-editing/youtube-thumbnails": { price: 0.04, unit: "images" },
  "fal-ai/image-preprocessors/depth-anything/v2": { price: 0, unit: "compute seconds" },
  "fal-ai/image-preprocessors/hed": { price: 0, unit: "compute seconds" },
  "fal-ai/image-preprocessors/lineart": { price: 0, unit: "compute seconds" },
  "fal-ai/image-preprocessors/midas": { price: 0, unit: "compute seconds" },
  "fal-ai/image-preprocessors/mlsd": { price: 0, unit: "compute seconds" },
  "fal-ai/image-preprocessors/pidi": { price: 0, unit: "compute seconds" },
  "fal-ai/image-preprocessors/sam": { price: 0, unit: "compute seconds" },
  "fal-ai/image-preprocessors/scribble": { price: 0, unit: "compute seconds" },
  "fal-ai/image-preprocessors/teed": { price: 0, unit: "compute seconds" },
  "fal-ai/image-preprocessors/zoe": { price: 0, unit: "compute seconds" },
  "fal-ai/image2pixel": { price: 0, unit: "compute seconds" },
  "fal-ai/image2svg": { price: 0.005, unit: "images" },
  "fal-ai/imageutils/depth": { price: 0, unit: "compute seconds" },
  "fal-ai/imageutils/marigold-depth": { price: 0, unit: "compute seconds" },
  "fal-ai/imageutils/rembg": { price: 0, unit: "compute seconds" },
  "fal-ai/infinitalk/single-text": { price: 0.2, unit: "seconds" },
  "fal-ai/infinity-star/text-to-video": { price: 0.07, unit: "videos" },
  "fal-ai/inpaint": { price: 0, unit: "compute seconds" },
  "fal-ai/instant-character": { price: 0.1, unit: "megapixels" },
  "fal-ai/ip-adapter-face-id": { price: 0, unit: "compute seconds" },
  "fal-ai/janus": { price: 0, unit: "compute seconds" },
  "fal-ai/joyai-image-edit": { price: 0.1, unit: "megapixels" },
  "fal-ai/kandinsky5-pro/image-to-video": { price: 0.2, unit: "videos" },
  "fal-ai/kandinsky5-pro/text-to-video": { price: 0.2, unit: "videos" },
  "fal-ai/kandinsky5/text-to-video": { price: 0.08, unit: "videos" },
  "fal-ai/kandinsky5/text-to-video/distill": { price: 0.05, unit: "videos" },
  "fal-ai/kling-image/o1": { price: 0.028, unit: "images" },
  "fal-ai/kling-image/o3/image-to-image": { price: 0.028, unit: "images" },
  "fal-ai/kling-image/o3/text-to-image": { price: 0.028, unit: "images" },
  "fal-ai/kling-image/v3/image-to-image": { price: 0.028, unit: "images" },
  "fal-ai/kling-image/v3/text-to-image": { price: 0.028, unit: "images" },
  "fal-ai/kling-video/ai-avatar/v2/pro": { price: 0.115, unit: "seconds" },
  "fal-ai/kling-video/ai-avatar/v2/standard": { price: 0.0562, unit: "seconds" },
  "fal-ai/kling-video/lipsync/audio-to-video": { price: 0.014, unit: "units" },
  "fal-ai/kling-video/lipsync/text-to-video": { price: 0.014, unit: "units" },
  "fal-ai/kling-video/o1/image-to-video": { price: 0.112, unit: "seconds" },
  "fal-ai/kling-video/o1/reference-to-video": { price: 0.112, unit: "seconds" },
  "fal-ai/kling-video/o1/standard/image-to-video": { price: 0.084, unit: "seconds" },
  "fal-ai/kling-video/o1/standard/reference-to-video": { price: 0.084, unit: "seconds" },
  "fal-ai/kling-video/o3/4k/image-to-video": { price: 0.42, unit: "seconds" },
  "fal-ai/kling-video/o3/4k/reference-to-video": { price: 0.42, unit: "seconds" },
  "fal-ai/kling-video/o3/4k/text-to-video": { price: 0.42, unit: "seconds" },
  "fal-ai/kling-video/o3/pro/image-to-video": { price: 0.14, unit: "seconds" },
  "fal-ai/kling-video/o3/pro/reference-to-video": { price: 0.14, unit: "seconds" },
  "fal-ai/kling-video/o3/pro/text-to-video": { price: 0.14, unit: "seconds" },
  "fal-ai/kling-video/o3/standard/image-to-video": { price: 0.14, unit: "seconds" },
  "fal-ai/kling-video/o3/standard/reference-to-video": { price: 0.14, unit: "seconds" },
  "fal-ai/kling-video/o3/standard/text-to-video": { price: 0.14, unit: "seconds" },
  "fal-ai/kling-video/v1.5/pro/effects": { price: 0.1, unit: "seconds" },
  "fal-ai/kling-video/v1.5/pro/image-to-video": { price: 0.1, unit: "seconds" },
  "fal-ai/kling-video/v1.5/pro/text-to-video": { price: 0.1, unit: "seconds" },
  "fal-ai/kling-video/v1.6/pro/effects": { price: 0.098, unit: "seconds" },
  "fal-ai/kling-video/v1.6/pro/elements": { price: 0.098, unit: "seconds" },
  "fal-ai/kling-video/v1.6/pro/image-to-video": { price: 0.098, unit: "seconds" },
  "fal-ai/kling-video/v1.6/pro/text-to-video": { price: 0.098, unit: "seconds" },
  "fal-ai/kling-video/v1.6/standard/effects": { price: 0.056, unit: "seconds" },
  "fal-ai/kling-video/v1.6/standard/elements": { price: 0.056, unit: "seconds" },
  "fal-ai/kling-video/v1.6/standard/image-to-video": { price: 0.056, unit: "seconds" },
  "fal-ai/kling-video/v1.6/standard/text-to-video": { price: 0.056, unit: "seconds" },
  "fal-ai/kling-video/v1/pro/ai-avatar": { price: 0.115, unit: "seconds" },
  "fal-ai/kling-video/v1/standard/ai-avatar": { price: 0.0562, unit: "seconds" },
  "fal-ai/kling-video/v1/standard/effects": { price: 0.045, unit: "seconds" },
  "fal-ai/kling-video/v1/standard/image-to-video": { price: 0.045, unit: "seconds" },
  "fal-ai/kling-video/v1/standard/text-to-video": { price: 0.045, unit: "seconds" },
  "fal-ai/kling-video/v2.1/master/image-to-video": { price: 0.28, unit: "seconds" },
  "fal-ai/kling-video/v2.1/master/text-to-video": { price: 0.28, unit: "seconds" },
  "fal-ai/kling-video/v2.1/pro/image-to-video": { price: 0.098, unit: "seconds" },
  "fal-ai/kling-video/v2.1/standard/image-to-video": { price: 0.056, unit: "seconds" },
  "fal-ai/kling-video/v2.5-turbo/pro/image-to-video": { price: 0.07, unit: "seconds" },
  "fal-ai/kling-video/v2.5-turbo/pro/text-to-video": { price: 0.07, unit: "seconds" },
  "fal-ai/kling-video/v2.5-turbo/standard/image-to-video": { price: 0.042, unit: "seconds" },
  "fal-ai/kling-video/v2.6/pro/image-to-video": { price: 0.07, unit: "seconds" },
  "fal-ai/kling-video/v2.6/pro/text-to-video": { price: 0.07, unit: "seconds" },
  "fal-ai/kling-video/v2/master/image-to-video": { price: 0.28, unit: "seconds" },
  "fal-ai/kling-video/v2/master/text-to-video": { price: 0.28, unit: "seconds" },
  "fal-ai/kling-video/v3/4k/image-to-video": { price: 0.42, unit: "seconds" },
  "fal-ai/kling-video/v3/4k/text-to-video": { price: 0.42, unit: "seconds" },
  "fal-ai/kling-video/v3/pro/image-to-video": { price: 0.14, unit: "seconds" },
  "fal-ai/kling-video/v3/pro/text-to-video": { price: 0.14, unit: "seconds" },
  "fal-ai/kling-video/v3/standard/image-to-video": { price: 0.14, unit: "seconds" },
  "fal-ai/kling-video/v3/standard/text-to-video": { price: 0.14, unit: "seconds" },
  "fal-ai/kling-video/v3/turbo/pro/image-to-video": { price: 0.14, unit: "seconds" },
  "fal-ai/kling-video/v3/turbo/pro/text-to-video": { price: 0.14, unit: "seconds" },
  "fal-ai/kling-video/v3/turbo/standard/image-to-video": { price: 0.112, unit: "seconds" },
  "fal-ai/kling-video/v3/turbo/standard/text-to-video": { price: 0.112, unit: "seconds" },
  "fal-ai/kling/v1-5/kolors-virtual-try-on": { price: 0.07, unit: "generations" },
  "fal-ai/kolors": { price: 0, unit: "compute seconds" },
  "fal-ai/kolors/image-to-image": { price: 0, unit: "compute seconds" },
  "fal-ai/krea-2/turbo": { price: 0.008, unit: "megapixels" },
  "fal-ai/krea-2/turbo/lora": { price: 0.01, unit: "megapixels" },
  "fal-ai/krea-2/turbo/style": { price: 0.01, unit: "megapixels" },
  "fal-ai/krea-wan-14b/text-to-video": { price: 0.025, unit: "seconds" },
  "fal-ai/lcm-sd15-i2i": { price: 0, unit: "compute seconds" },
  "fal-ai/leffa/pose-transfer": { price: 0.1, unit: "generations" },
  "fal-ai/leffa/virtual-tryon": { price: 0.1, unit: "generations" },
  "fal-ai/live-portrait": { price: 0, unit: "compute seconds" },
  "fal-ai/live-portrait/image": { price: 0, unit: "compute seconds" },
  "fal-ai/longcat-image": { price: 0.13, unit: "megapixels" },
  "fal-ai/longcat-image/edit": { price: 0.15, unit: "megapixels" },
  "fal-ai/longcat-video/distilled/image-to-video/480p": { price: 0.005, unit: "seconds" },
  "fal-ai/longcat-video/distilled/image-to-video/720p": { price: 0.01, unit: "seconds" },
  "fal-ai/longcat-video/distilled/text-to-video/480p": { price: 0.005, unit: "seconds" },
  "fal-ai/longcat-video/distilled/text-to-video/720p": { price: 0.01, unit: "seconds" },
  "fal-ai/longcat-video/image-to-video/480p": { price: 0.025, unit: "seconds" },
  "fal-ai/longcat-video/image-to-video/720p": { price: 0.04, unit: "seconds" },
  "fal-ai/longcat-video/text-to-video/480p": { price: 0.025, unit: "seconds" },
  "fal-ai/longcat-video/text-to-video/720p": { price: 0.04, unit: "seconds" },
  "fal-ai/lora": { price: 0, unit: "compute seconds" },
  "fal-ai/lora/image-to-image": { price: 0, unit: "compute seconds" },
  "fal-ai/lora/inpaint": { price: 0, unit: "compute seconds" },
  "fal-ai/ltx-2-19b/distilled/image-to-video": { price: 0.0008, unit: "megapixels" },
  "fal-ai/ltx-2-19b/distilled/image-to-video/lora": { price: 0.001, unit: "megapixels" },
  "fal-ai/ltx-2-19b/distilled/text-to-video": { price: 0.0008, unit: "megapixels" },
  "fal-ai/ltx-2-19b/distilled/text-to-video/lora": { price: 0.001, unit: "megapixels" },
  "fal-ai/ltx-2-19b/image-to-video": { price: 0.0018, unit: "megapixels" },
  "fal-ai/ltx-2-19b/image-to-video/lora": { price: 0.002, unit: "megapixels" },
  "fal-ai/ltx-2-19b/text-to-video": { price: 0.0018, unit: "megapixels" },
  "fal-ai/ltx-2-19b/text-to-video/lora": { price: 0.002, unit: "megapixels" },
  "fal-ai/ltx-2.3-22b/distilled/image-to-video": { price: 0.001205, unit: "megapixels" },
  "fal-ai/ltx-2.3-22b/distilled/image-to-video/lora": { price: 0.001405, unit: "megapixels" },
  "fal-ai/ltx-2.3-22b/distilled/text-to-video": { price: 0.001205, unit: "megapixels" },
  "fal-ai/ltx-2.3-22b/distilled/text-to-video/lora": { price: 0.001405, unit: "megapixels" },
  "fal-ai/ltx-2.3-22b/image-to-video": { price: 0.001605, unit: "megapixels" },
  "fal-ai/ltx-2.3-22b/image-to-video/lora": { price: 0.001805, unit: "megapixels" },
  "fal-ai/ltx-2.3-22b/text-to-video": { price: 0.001605, unit: "megapixels" },
  "fal-ai/ltx-2.3-22b/text-to-video/lora": { price: 0.001805, unit: "megapixels" },
  "fal-ai/ltx-2.3-quality/image-to-video": { price: 0.0024075, unit: "megapixels" },
  "fal-ai/ltx-2.3-quality/image-to-video/lora": { price: 0.0027075, unit: "megapixels" },
  "fal-ai/ltx-2.3-quality/ingredient": { price: 0.0024075, unit: "megapixels" },
  "fal-ai/ltx-2.3-quality/text-to-video": { price: 0.0024075, unit: "megapixels" },
  "fal-ai/ltx-2.3-quality/text-to-video/lora": { price: 0.0027075, unit: "megapixels" },
  "fal-ai/ltx-2.3/image-to-video": { price: 0.08, unit: "seconds" },
  "fal-ai/ltx-2.3/image-to-video/fast": { price: 0.06, unit: "seconds" },
  "fal-ai/ltx-2.3/text-to-video": { price: 0.08, unit: "seconds" },
  "fal-ai/ltx-2.3/text-to-video/fast": { price: 0.06, unit: "seconds" },
  "fal-ai/ltx-video": { price: 0.02, unit: "videos" },
  "fal-ai/ltx-video-13b-distilled": { price: 0.04, unit: "videos" },
  "fal-ai/ltx-video-13b-distilled/image-to-video": { price: 0.04, unit: "units" },
  "fal-ai/ltx-video-v095": { price: 0.04, unit: "videos" },
  "fal-ai/ltx-video/image-to-video": { price: 0.02, unit: "videos" },
  "fal-ai/ltxv-13b-098-distilled": { price: 0.02, unit: "seconds" },
  "fal-ai/ltxv-13b-098-distilled/image-to-video": { price: 0.02, unit: "seconds" },
  "fal-ai/luma-dream-machine/ray-2": { price: 0.5, unit: "5 seconds" },
  "fal-ai/luma-dream-machine/ray-2-flash": { price: 0.2, unit: "5 seconds" },
  "fal-ai/luma-dream-machine/ray-2-flash/image-to-video": { price: 0.2, unit: "5 seconds" },
  "fal-ai/luma-dream-machine/ray-2/image-to-video": { price: 0.5, unit: "5 seconds" },
  "fal-ai/luma-photon": { price: 0.019, unit: "megapixels" },
  "fal-ai/luma-photon/flash": { price: 0.005, unit: "megapixels" },
  "fal-ai/luma-photon/flash/modify": { price: 0.005, unit: "megapixels" },
  "fal-ai/luma-photon/flash/reframe": { price: 0.005, unit: "megapixels" },
  "fal-ai/luma-photon/modify": { price: 0.019, unit: "megapixels" },
  "fal-ai/luma-photon/reframe": { price: 0.019, unit: "megapixels" },
  "fal-ai/lumina-image/v2": { price: 0.075, unit: "megapixels" },
  "fal-ai/magi-distilled": { price: 0.08, unit: "seconds" },
  "fal-ai/magi-distilled/image-to-video": { price: 0.08, unit: "seconds" },
  "fal-ai/minimax/hailuo-02-fast/image-to-video": { price: 0.017, unit: "seconds" },
  "fal-ai/minimax/hailuo-02/pro/image-to-video": { price: 0.08, unit: "seconds" },
  "fal-ai/minimax/hailuo-02/pro/text-to-video": { price: 0.08, unit: "seconds" },
  "fal-ai/minimax/hailuo-02/standard/image-to-video": { price: 0.045, unit: "seconds" },
  "fal-ai/minimax/hailuo-02/standard/text-to-video": { price: 0.045, unit: "seconds" },
  "fal-ai/minimax/hailuo-2.3-fast/pro/image-to-video": { price: 0.33, unit: "videos" },
  "fal-ai/minimax/hailuo-2.3-fast/standard/image-to-video": { price: 0.19, unit: "units" },
  "fal-ai/minimax/hailuo-2.3/pro/image-to-video": { price: 0.49, unit: "units" },
  "fal-ai/minimax/hailuo-2.3/pro/text-to-video": { price: 0.49, unit: "units" },
  "fal-ai/minimax/hailuo-2.3/standard/image-to-video": { price: 0.28, unit: "units" },
  "fal-ai/minimax/hailuo-2.3/standard/text-to-video": { price: 0.28, unit: "units" },
  "fal-ai/minimax/image-01": { price: 0.01, unit: "images" },
  "fal-ai/minimax/image-01/subject-reference": { price: 0.01, unit: "images" },
  "fal-ai/minimax/video-01": { price: 0.5, unit: "videos" },
  "fal-ai/minimax/video-01-director": { price: 0.5, unit: "videos" },
  "fal-ai/minimax/video-01-director/image-to-video": { price: 0.5, unit: "videos" },
  "fal-ai/minimax/video-01-live": { price: 0.5, unit: "videos" },
  "fal-ai/minimax/video-01-live/image-to-video": { price: 0.5, unit: "videos" },
  "fal-ai/minimax/video-01-subject-reference": { price: 0.5, unit: "videos" },
  "fal-ai/minimax/video-01/image-to-video": { price: 0.5, unit: "videos" },
  "fal-ai/moondream-next/detection": { price: 0.0011, unit: "seconds" },
  "fal-ai/moondream3-preview/segment": { price: 1, unit: "units" },
  "fal-ai/musetalk": { price: 0, unit: "compute seconds" },
  "fal-ai/nafnet/deblur": { price: 0.0225, unit: "megapixels" },
  "fal-ai/nafnet/denoise": { price: 0.0225, unit: "megapixels" },
  "fal-ai/nano-banana": { price: 0.0398, unit: "images" },
  "fal-ai/nano-banana-2": { price: 0.08, unit: "images", multipliers: {"512":0.75,"2K":1.5,"4K":2} },
  "fal-ai/nano-banana-2/edit": { price: 0.08, unit: "images", multipliers: {"512":0.75,"2K":1.5,"4K":2} },
  "fal-ai/nano-banana-pro": { price: 0.15, unit: "images" },
  "fal-ai/nano-banana-pro/edit": { price: 0.15, unit: "images" },
  "fal-ai/nano-banana/edit": { price: 0.0398, unit: "images" },
  "fal-ai/nucleus-image": { price: 0.01, unit: "megapixels" },
  "fal-ai/object-removal": { price: 0.006, unit: "images" },
  "fal-ai/object-removal/bbox": { price: 0.006, unit: "images" },
  "fal-ai/object-removal/mask": { price: 0.006, unit: "images" },
  "fal-ai/omni-zero": { price: 0, unit: "compute seconds" },
  "fal-ai/omnigen-v1": { price: 0.1, unit: "processed megapixels" },
  "fal-ai/omnigen-v2": { price: 0.15, unit: "megapixels" },
  "fal-ai/ovi": { price: 0.2, unit: "videos" },
  "fal-ai/ovi/image-to-video": { price: 0.2, unit: "videos" },
  "fal-ai/ovis-image": { price: 0.012, unit: "megapixels" },
  "fal-ai/pasd": { price: 0.03, unit: "megapixels" },
  "fal-ai/patina": { price: 0.01, unit: "megapixels" },
  "fal-ai/patina/material": { price: 0.01, unit: "megapixels" },
  "fal-ai/patina/material/extract": { price: 0.01, unit: "megapixels" },
  "fal-ai/phota": { price: 0.09, unit: "units" },
  "fal-ai/phota/edit": { price: 0.09, unit: "units" },
  "fal-ai/phota/enhance": { price: 0.13, unit: "images" },
  "fal-ai/photomaker": { price: 0, unit: "compute seconds" },
  "fal-ai/pika/v2.1/image-to-video": { price: 0.4, unit: "videos" },
  "fal-ai/pika/v2.1/text-to-video": { price: 0.4, unit: "videos" },
  "fal-ai/pika/v2.2/image-to-video": { price: 0.2, unit: "videos" },
  "fal-ai/pika/v2.2/pikaframes": { price: 0.2, unit: "videos" },
  "fal-ai/pika/v2.2/pikascenes": { price: 0.2, unit: "videos" },
  "fal-ai/pika/v2.2/text-to-video": { price: 0.2, unit: "videos" },
  "fal-ai/pika/v2/turbo/image-to-video": { price: 0.2, unit: "videos" },
  "fal-ai/pika/v2/turbo/text-to-video": { price: 0.2, unit: "videos" },
  "fal-ai/pixart-sigma": { price: 0, unit: "compute seconds" },
  "fal-ai/pixverse/c1/image-to-video": { price: 0.005, unit: "seconds" },
  "fal-ai/pixverse/c1/reference-to-video": { price: 0.005, unit: "seconds" },
  "fal-ai/pixverse/c1/text-to-video": { price: 0.005, unit: "seconds" },
  "fal-ai/pixverse/c1/transition": { price: 0.005, unit: "seconds" },
  "fal-ai/pixverse/swap": { price: 0.05, unit: "videos" },
  "fal-ai/pixverse/v3.5/effects": { price: 0.05, unit: "video segments" },
  "fal-ai/pixverse/v3.5/image-to-video": { price: 0.05, unit: "video segments" },
  "fal-ai/pixverse/v3.5/image-to-video/fast": { price: 0.1, unit: "video segments" },
  "fal-ai/pixverse/v3.5/text-to-video": { price: 0.05, unit: "video segments" },
  "fal-ai/pixverse/v3.5/text-to-video/fast": { price: 0.1, unit: "video segments" },
  "fal-ai/pixverse/v3.5/transition": { price: 0.05, unit: "video segments" },
  "fal-ai/pixverse/v4.5/effects": { price: 0.05, unit: "video segments" },
  "fal-ai/pixverse/v4.5/image-to-video": { price: 0.05, unit: "video segments" },
  "fal-ai/pixverse/v4.5/image-to-video/fast": { price: 0.1, unit: "video segments" },
  "fal-ai/pixverse/v4.5/text-to-video": { price: 0.05, unit: "video segments" },
  "fal-ai/pixverse/v4.5/text-to-video/fast": { price: 0.1, unit: "video segments" },
  "fal-ai/pixverse/v4.5/transition": { price: 0.05, unit: "video segments" },
  "fal-ai/pixverse/v4/effects": { price: 0.05, unit: "video segments" },
  "fal-ai/pixverse/v4/image-to-video": { price: 0.05, unit: "video segments" },
  "fal-ai/pixverse/v4/image-to-video/fast": { price: 0.1, unit: "video segments" },
  "fal-ai/pixverse/v4/text-to-video": { price: 0.05, unit: "video segments" },
  "fal-ai/pixverse/v4/text-to-video/fast": { price: 0.1, unit: "video segments" },
  "fal-ai/pixverse/v5.5/effects": { price: 0.05, unit: "videos" },
  "fal-ai/pixverse/v5.5/image-to-video": { price: 0.05, unit: "videos" },
  "fal-ai/pixverse/v5.5/text-to-video": { price: 0.05, unit: "videos" },
  "fal-ai/pixverse/v5.5/transition": { price: 0.05, unit: "videos" },
  "fal-ai/pixverse/v5.6/image-to-video": { price: 0.15, unit: "videos" },
  "fal-ai/pixverse/v5.6/text-to-video": { price: 0.15, unit: "videos" },
  "fal-ai/pixverse/v5.6/transition": { price: 0.15, unit: "videos" },
  "fal-ai/pixverse/v5/effects": { price: 0.05, unit: "video segments" },
  "fal-ai/pixverse/v5/image-to-video": { price: 0.05, unit: "video segments" },
  "fal-ai/pixverse/v5/text-to-video": { price: 0.05, unit: "video segments" },
  "fal-ai/pixverse/v5/transition": { price: 0.05, unit: "video segments" },
  "fal-ai/pixverse/v6/image-to-video": { price: 0.005, unit: "seconds" },
  "fal-ai/pixverse/v6/text-to-video": { price: 0.005, unit: "seconds" },
  "fal-ai/pixverse/v6/transition": { price: 0.005, unit: "seconds" },
  "fal-ai/playground-v25": { price: 0, unit: "compute seconds" },
  "fal-ai/playground-v25/image-to-image": { price: 0, unit: "compute seconds" },
  "fal-ai/playground-v25/inpainting": { price: 0, unit: "compute seconds" },
  "fal-ai/pony-v7": { price: 0.03, unit: "megapixels" },
  "fal-ai/post-processing": { price: 0.001, unit: "1" },
  "fal-ai/post-processing/blur": { price: 0.001, unit: "images" },
  "fal-ai/post-processing/chromatic-aberration": { price: 0.001, unit: "images" },
  "fal-ai/post-processing/color-correction": { price: 0.001, unit: "images" },
  "fal-ai/post-processing/color-tint": { price: 0.001, unit: "images" },
  "fal-ai/post-processing/desaturate": { price: 0.001, unit: "images" },
  "fal-ai/post-processing/dissolve": { price: 0.001, unit: "images" },
  "fal-ai/post-processing/dodge-burn": { price: 0.001, unit: "images" },
  "fal-ai/post-processing/grain": { price: 0.001, unit: "images" },
  "fal-ai/post-processing/parabolize": { price: 0.001, unit: "images" },
  "fal-ai/post-processing/sharpen": { price: 0.001, unit: "images" },
  "fal-ai/post-processing/solarize": { price: 0.001, unit: "images" },
  "fal-ai/post-processing/vignette": { price: 0.001, unit: "images" },
  "fal-ai/pulid": { price: 0, unit: "compute seconds" },
  "fal-ai/qwen-image": { price: 0.02, unit: "megapixels" },
  "fal-ai/qwen-image-2512": { price: 0.02, unit: "megapixels" },
  "fal-ai/qwen-image-2512/lora": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit": { price: 0.03, unit: "megapixels" },
  "fal-ai/qwen-image-edit-2509": { price: 0.03, unit: "megapixels" },
  "fal-ai/qwen-image-edit-2509-lora": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-2509-lora-gallery/add-background": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-2509-lora-gallery/face-to-full-portrait": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-2509-lora-gallery/group-photo": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-2509-lora-gallery/integrate-product": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-2509-lora-gallery/lighting-restoration": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-2509-lora-gallery/multiple-angles": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-2509-lora-gallery/next-scene": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-2509-lora-gallery/remove-element": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-2509-lora-gallery/remove-lighting": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-2509-lora-gallery/shirt-design": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-2511": { price: 0.03, unit: "megapixels" },
  "fal-ai/qwen-image-edit-2511-multiple-angles": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-2511/lora": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-lora": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-plus": { price: 0.03, unit: "megapixels" },
  "fal-ai/qwen-image-edit-plus-lora": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-plus-lora-gallery/add-background": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-plus-lora-gallery/face-to-full-portrait": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-plus-lora-gallery/group-photo": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-plus-lora-gallery/integrate-product": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-plus-lora-gallery/lighting-restoration": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-plus-lora-gallery/multiple-angles": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-plus-lora-gallery/next-scene": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-plus-lora-gallery/remove-element": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-plus-lora-gallery/remove-lighting": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit-plus-lora-gallery/shirt-design": { price: 0.035, unit: "megapixels" },
  "fal-ai/qwen-image-edit/image-to-image": { price: 0.03, unit: "megapixels" },
  "fal-ai/qwen-image-edit/inpaint": { price: 0.03, unit: "megapixels" },
  "fal-ai/qwen-image-layered": { price: 0.05, unit: "images" },
  "fal-ai/qwen-image-layered/lora": { price: 0.06, unit: "images" },
  "fal-ai/qwen-image-max/edit": { price: 0.075, unit: "images" },
  "fal-ai/qwen-image-max/text-to-image": { price: 0.075, unit: "images" },
  "fal-ai/qwen-image/image-to-image": { price: 0.02, unit: "megapixels" },
  "fal-ai/realistic-vision": { price: 0, unit: "compute seconds" },
  "fal-ai/recraft-20b": { price: 0.0219, unit: "images" },
  "fal-ai/recraft/upscale/creative": { price: 0.25, unit: "images" },
  "fal-ai/recraft/upscale/crisp": { price: 0.004, unit: "images" },
  "fal-ai/recraft/v3/image-to-image": { price: 0.04, unit: "images" },
  "fal-ai/recraft/v3/text-to-image": { price: 0.04, unit: "images" },
  "fal-ai/recraft/v4.1/pro/text-to-image": { price: 0.21, unit: "images" },
  "fal-ai/recraft/v4.1/pro/text-to-vector": { price: 0.3, unit: "images" },
  "fal-ai/recraft/v4.1/text-to-image": { price: 0.035, unit: "images" },
  "fal-ai/recraft/v4.1/text-to-vector": { price: 0.08, unit: "images" },
  "fal-ai/recraft/v4.1/utility/pro/text-to-image": { price: 0.21, unit: "images" },
  "fal-ai/recraft/v4.1/utility/text-to-image": { price: 0.035, unit: "images" },
  "fal-ai/recraft/v4/pro/text-to-image": { price: 0.25, unit: "images" },
  "fal-ai/recraft/v4/pro/text-to-vector": { price: 0.3, unit: "images" },
  "fal-ai/recraft/v4/text-to-image": { price: 0.04, unit: "images" },
  "fal-ai/recraft/v4/text-to-vector": { price: 0.08, unit: "images" },
  "fal-ai/recraft/vectorize": { price: 0.01, unit: "images" },
  "fal-ai/retoucher": { price: 0, unit: "compute seconds" },
  "fal-ai/rife": { price: 0.0013, unit: "seconds" },
  "fal-ai/sadtalker": { price: 0, unit: "compute seconds" },
  "fal-ai/sadtalker/reference": { price: 0, unit: "compute seconds" },
  "fal-ai/sam-3-1/image": { price: 0.01, unit: "units" },
  "fal-ai/sam-3-1/image-rle": { price: 0.01, unit: "units" },
  "fal-ai/sam-3/image": { price: 0.005, unit: "units" },
  "fal-ai/sam-3/image-rle": { price: 0.005, unit: "units" },
  "fal-ai/sam2/auto-segment": { price: 0, unit: "compute seconds" },
  "fal-ai/sam2/image": { price: 0, unit: "compute seconds" },
  "fal-ai/sana": { price: 0.001, unit: "megapixels" },
  "fal-ai/sana/sprint": { price: 0.0025, unit: "megapixels" },
  "fal-ai/sana/v1.5/1.6b": { price: 0.0075, unit: "megapixels" },
  "fal-ai/sana/v1.5/4.8b": { price: 0.01, unit: "megapixels" },
  "fal-ai/sdxl-controlnet-union": { price: 0, unit: "compute seconds" },
  "fal-ai/sdxl-controlnet-union/image-to-image": { price: 0, unit: "compute seconds" },
  "fal-ai/sdxl-controlnet-union/inpainting": { price: 0, unit: "compute seconds" },
  "fal-ai/seedvr/upscale/image": { price: 0.001, unit: "megapixels" },
  "fal-ai/seedvr/upscale/image/seamless": { price: 0.0025, unit: "megapixels" },
  "fal-ai/sensenova-u1-infographic": { price: 0.05, unit: "images" },
  "fal-ai/smart-resize": { price: 0.15, unit: "images" },
  "fal-ai/stable-cascade": { price: 0, unit: "compute seconds" },
  "fal-ai/stable-cascade/sote-diffusion": { price: 0, unit: "compute seconds" },
  "fal-ai/stable-diffusion-v15": { price: 0, unit: "compute seconds" },
  "fal-ai/stable-diffusion-v3-medium": { price: 0.035, unit: "images" },
  "fal-ai/stable-diffusion-v3-medium/image-to-image": { price: 0.035, unit: "images" },
  "fal-ai/stable-diffusion-v35-large": { price: 0.065, unit: "megapixels" },
  "fal-ai/stable-diffusion-v35-medium": { price: 0.02, unit: "megapixels" },
  "fal-ai/stable-video": { price: 0.075, unit: "videos" },
  "fal-ai/stepx-edit2": { price: 0.2, unit: "megapixels" },
  "fal-ai/sync-lipsync/v3/image-to-video": { price: 8, unit: "minutes" },
  "fal-ai/t2v-turbo": { price: 0, unit: "compute seconds" },
  "fal-ai/telestyle-v2": { price: 0.035, unit: "megapixels" },
  "fal-ai/uno": { price: 0.05, unit: "megapixels" },
  "fal-ai/uso": { price: 0.1, unit: "megapixels" },
  "fal-ai/vecglypher": { price: 0.005, unit: "images" },
  "fal-ai/vecglypher/image-to-svg": { price: 0.005, unit: "images" },
  "fal-ai/veo3.1": { price: 0.4, unit: "seconds" },
  "fal-ai/veo3.1/fast": { price: 0.15, unit: "seconds" },
  "fal-ai/veo3.1/fast/first-last-frame-to-video": { price: 0.15, unit: "seconds" },
  "fal-ai/veo3.1/fast/image-to-video": { price: 0.15, unit: "seconds" },
  "fal-ai/veo3.1/fast/reference-to-video": { price: 0.15, unit: "seconds" },
  "fal-ai/veo3.1/first-last-frame-to-video": { price: 0.4, unit: "seconds" },
  "fal-ai/veo3.1/image-to-video": { price: 0.4, unit: "seconds" },
  "fal-ai/veo3.1/lite": { price: 0.05, unit: "seconds" },
  "fal-ai/veo3.1/lite/first-last-frame-to-video": { price: 0.05, unit: "seconds" },
  "fal-ai/veo3.1/lite/image-to-video": { price: 0.05, unit: "seconds" },
  "fal-ai/veo3.1/reference-to-video": { price: 0.4, unit: "seconds" },
  "fal-ai/vidu/image-to-video": { price: 0.05, unit: "" },
  "fal-ai/vidu/q1/image-to-video": { price: 0.05, unit: "credits" },
  "fal-ai/vidu/q1/reference-to-video": { price: 0.05, unit: "credits" },
  "fal-ai/vidu/q1/start-end-to-video": { price: 0.05, unit: "credits" },
  "fal-ai/vidu/q1/text-to-video": { price: 0.05, unit: "credits" },
  "fal-ai/vidu/q2/image-to-video/pro": { price: 0.05, unit: "videos" },
  "fal-ai/vidu/q2/image-to-video/turbo": { price: 0.05, unit: "videos" },
  "fal-ai/vidu/q2/reference-to-image": { price: 0.05, unit: "images" },
  "fal-ai/vidu/q2/reference-to-video/pro": { price: 0.1, unit: "videos" },
  "fal-ai/vidu/q2/text-to-image": { price: 0.05, unit: "images" },
  "fal-ai/vidu/q2/text-to-video": { price: 0.1, unit: "videos" },
  "fal-ai/vidu/q3/image-to-video": { price: 0.07, unit: "videos" },
  "fal-ai/vidu/q3/image-to-video/turbo": { price: 0.035, unit: "videos" },
  "fal-ai/vidu/q3/reference-to-video/mix": { price: 0.07, unit: "videos" },
  "fal-ai/vidu/q3/text-to-video": { price: 0.07, unit: "videos" },
  "fal-ai/vidu/q3/text-to-video/turbo": { price: 0.035, unit: "videos" },
  "fal-ai/vidu/reference-to-image": { price: 0.05, unit: "images" },
  "fal-ai/vidu/reference-to-video": { price: 0.05, unit: "" },
  "fal-ai/vidu/start-end-to-video": { price: 0.05, unit: "" },
  "fal-ai/vidu/template-to-video": { price: 0.05, unit: "" },
  "fal-ai/wan-25-preview/image-to-image": { price: 0.05, unit: "images" },
  "fal-ai/wan-25-preview/image-to-video": { price: 0.05, unit: "seconds" },
  "fal-ai/wan-25-preview/text-to-image": { price: 0.05, unit: "images" },
  "fal-ai/wan-25-preview/text-to-video": { price: 0.05, unit: "seconds" },
  "fal-ai/wan-effects": { price: 0.35, unit: "videos" },
  "fal-ai/wan-flf2v": { price: 0.4, unit: "videos" },
  "fal-ai/wan-i2v": { price: 0.4, unit: "videos" },
  "fal-ai/wan-i2v-lora": { price: 0.75, unit: "videos" },
  "fal-ai/wan-pro/image-to-video": { price: 0.8, unit: "videos" },
  "fal-ai/wan-pro/text-to-video": { price: 0.8, unit: "5 seconds" },
  "fal-ai/wan-t2v": { price: 0.4, unit: "videos" },
  "fal-ai/wan-t2v-lora": { price: 0.75, unit: "videos" },
  "fal-ai/wan/v2.2-5b/image-to-video": { price: 0.15, unit: "videos" },
  "fal-ai/wan/v2.2-5b/text-to-image": { price: 0.016, unit: "images" },
  "fal-ai/wan/v2.2-5b/text-to-video": { price: 0.15, unit: "videos" },
  "fal-ai/wan/v2.2-5b/text-to-video/distill": { price: 0.08, unit: "videos" },
  "fal-ai/wan/v2.2-5b/text-to-video/fast-wan": { price: 0.025, unit: "videos" },
  "fal-ai/wan/v2.2-a14b/image-to-image": { price: 0.05, unit: "images" },
  "fal-ai/wan/v2.2-a14b/image-to-video": { price: 0.08, unit: "seconds" },
  "fal-ai/wan/v2.2-a14b/image-to-video/lora": { price: 0.1, unit: "seconds" },
  "fal-ai/wan/v2.2-a14b/image-to-video/turbo": { price: 0.1, unit: "videos" },
  "fal-ai/wan/v2.2-a14b/text-to-image": { price: 0.025, unit: "images" },
  "fal-ai/wan/v2.2-a14b/text-to-image/lora": { price: 0.05, unit: "images" },
  "fal-ai/wan/v2.2-a14b/text-to-video": { price: 0.08, unit: "seconds" },
  "fal-ai/wan/v2.2-a14b/text-to-video/lora": { price: 0.1, unit: "seconds" },
  "fal-ai/wan/v2.2-a14b/text-to-video/turbo": { price: 0.1, unit: "videos" },
  "fal-ai/wan/v2.7/edit": { price: 0.03, unit: "images" },
  "fal-ai/wan/v2.7/image-to-video": { price: 0.1, unit: "seconds" },
  "fal-ai/wan/v2.7/pro/edit": { price: 0.075, unit: "images" },
  "fal-ai/wan/v2.7/pro/text-to-image": { price: 0.075, unit: "images" },
  "fal-ai/wan/v2.7/reference-to-video": { price: 0.1, unit: "seconds" },
  "fal-ai/wan/v2.7/text-to-image": { price: 0.03, unit: "images" },
  "fal-ai/wan/v2.7/text-to-video": { price: 0.1, unit: "seconds" },
  "fal-ai/workflow-utilities/extract-nth-frame": { price: 0.001, unit: "compute seconds" },
  "fal-ai/z-image/base": { price: 0.01, unit: "megapixels" },
  "fal-ai/z-image/base/lora": { price: 0.012, unit: "megapixels" },
  "fal-ai/z-image/turbo": { price: 0.005, unit: "megapixels" },
  "fal-ai/z-image/turbo/controlnet": { price: 0.0065, unit: "megapixels" },
  "fal-ai/z-image/turbo/controlnet/lora": { price: 0.01, unit: "megapixels" },
  "fal-ai/z-image/turbo/image-to-image": { price: 0.005, unit: "megapixels" },
  "fal-ai/z-image/turbo/image-to-image/lora": { price: 0.0085, unit: "megapixels" },
  "fal-ai/z-image/turbo/inpaint": { price: 0.01, unit: "megapixels" },
  "fal-ai/z-image/turbo/inpaint/lora": { price: 0.0115, unit: "megapixels" },
  "fal-ai/z-image/turbo/lora": { price: 0.0085, unit: "megapixels" },
  "fal-ai/z-image/turbo/tiling": { price: 0.02, unit: "megapixels" },
  "fal-ai/z-image/turbo/tiling/lora": { price: 0.025, unit: "megapixels" },
  "google/gemini-omni-flash": { price: 1, unit: "units" },
  "google/gemini-omni-flash/image-to-video": { price: 1, unit: "units" },
  "google/gemini-omni-flash/reference-to-video": { price: 1, unit: "units" },
  "google/nano-banana-2-lite": { price: 1, unit: "units" },
  "google/nano-banana-lite": { price: 1, unit: "units" },
  "google/nano-banana-lite/edit": { price: 1, unit: "units" },
  "hitem3d/hi3d/image-to-relief": { price: 0.02, unit: "credits" },
  "ideogram/v4": { price: 0.01, unit: "units" },
  "ideogram/v4/fast": { price: 0.007, unit: "units" },
  "ideogram/v4/image-to-image": { price: 0.01, unit: "units" },
  "ideogram/v4/image-to-image/lora": { price: 0.015, unit: "units" },
  "ideogram/v4/instant": { price: 0.005, unit: "units" },
  "ideogram/v4/lora": { price: 0.015, unit: "units" },
  "ideogram/v4/tiling": { price: 0.04, unit: "images" },
  "ideogram/v4/tiling/lora": { price: 0.045, unit: "images" },
  "imagineart/imagineart-1.5-preview/text-to-image": { price: 0.03, unit: "images" },
  "imagineart/imagineart-1.5-pro-preview/text-to-image": { price: 0.045, unit: "images" },
  "imagineart/imagineart-2.0-edit-preview/image-to-image": { price: 0.001, unit: "images" },
  "imagineart/imagineart-2.0-preview/text-to-image": { price: 0.03, unit: "units" },
  "krea/v2/large/text-to-image": { price: 0.001, unit: "units" },
  "krea/v2/medium/text-to-image": { price: 0.001, unit: "units" },
  "krea/v2/medium/turbo/text-to-image": { price: 0.001, unit: "units" },
  "lightricks/ltx-2.5/image-to-video/fast": { price: 0.01, unit: "units" },
  "lightricks/ltx-2.5/image-to-video/pro": { price: 0.01, unit: "units" },
  "lightricks/ltx-2.5/text-to-video/fast": { price: 0.01, unit: "units" },
  "lightricks/ltx-2.5/text-to-video/pro": { price: 0.01, unit: "units" },
  "luma/agent/ray/v3.2/image-to-video": { price: 0.03, unit: "seconds" },
  "luma/agent/ray/v3.2/text-to-video": { price: 0.03, unit: "seconds" },
  "luma/agent/uni-1/v1/edit": { price: 0.003, unit: "images" },
  "luma/agent/uni-1/v1/max": { price: 0.003, unit: "images" },
  "luma/agent/uni-1/v1/max/edit": { price: 0.003, unit: "images" },
  "luma/agent/uni-1/v1/text-to-image": { price: 0.003, unit: "images" },
  "microsoft/mai-image-2.5": { price: 1, unit: "credits" },
  "microsoft/mai-image-2.5-pro": { price: 1.5, unit: "credits" },
  "microsoft/mai-image-2.5-pro/edit": { price: 1.5, unit: "credits" },
  "microsoft/mai-image-2.5/edit": { price: 1, unit: "credits" },
  "minimax/h3/image-to-video": { price: 0.05, unit: "seconds" },
  "minimax/h3/image-to-video/lora": { price: 0.0625, unit: "seconds" },
  "minimax/h3/reference-to-video": { price: 0.05, unit: "seconds" },
  "minimax/h3/text-to-video": { price: 0.05, unit: "seconds" },
  "minimax/h3/text-to-video/lora": { price: 0.0625, unit: "seconds" },
  "mirage-api/avatar-x/reference-to-video": { price: 0.3, unit: "seconds" },
  "mirage-api/avatar-x/text-to-video": { price: 0.3, unit: "seconds" },
  "moonvalley/marey/i2v": { price: 1.5, unit: "5 seconds" },
  "moonvalley/marey/t2v": { price: 1.5, unit: "5 seconds" },
  "nvidia/cosmos-3-super/image-to-video": { price: 0.05, unit: "seconds" },
  "nvidia/cosmos-3-super/text-to-image": { price: 0.04, unit: "images" },
  "openai/gpt-image-2": { price: 1, unit: "units" },
  "openai/gpt-image-2/edit": { price: 1, unit: "units" },
  "pixelcut/background-removal": { price: 0.016, unit: "images" },
  "pixelcut/product-photo": { price: 0.024, unit: "images" },
  "reve/2.1/edit": { price: 0.25, unit: "images" },
  "reve/2.1/remix": { price: 0.25, unit: "images" },
  "reve/2.1/text-to-image": { price: 0.25, unit: "images" },
  "rundiffusion-fal/juggernaut-flux-lora": { price: 0.045, unit: "megapixels" },
  "rundiffusion-fal/juggernaut-flux-lora/inpainting": { price: 0.045, unit: "megapixels" },
  "rundiffusion-fal/juggernaut-flux/base": { price: 0.035, unit: "megapixels" },
  "rundiffusion-fal/juggernaut-flux/base/image-to-image": { price: 0.035, unit: "megapixels" },
  "rundiffusion-fal/juggernaut-flux/lightning": { price: 0.006, unit: "megapixels" },
  "rundiffusion-fal/juggernaut-flux/pro": { price: 0.055, unit: "megapixels" },
  "rundiffusion-fal/juggernaut-flux/pro/image-to-image": { price: 0.055, unit: "megapixels" },
  "rundiffusion-fal/rundiffusion-photo-flux": { price: 0.045, unit: "megapixels" },
  "smoretalk-ai/rembg-enhance": { price: 0.006, unit: "generations" },
  "topaz/adjust/image": { price: 0.01, unit: "units" },
  "topaz/denoise/image": { price: 0.01, unit: "units" },
  "topaz/restore/image": { price: 0.01, unit: "units" },
  "topaz/sharpen/image": { price: 0.01, unit: "units" },
  "topaz/upscale/image/creative": { price: 0.01, unit: "units" },
  "topaz/upscale/image/generative": { price: 0.01, unit: "units" },
  "topaz/upscale/image/precision": { price: 0.01, unit: "units" },
  "topaz/upscale/image/transparent": { price: 0.01, unit: "units" },
  "veed/avatars/text-to-video": { price: 0.35, unit: "minutes" },
  "veed/fabric-1.0": { price: 0.08, unit: "seconds" },
  "veed/fabric-1.0/fast": { price: 0.1, unit: "seconds" },
  "veed/fabric-1.0/text": { price: 0.08, unit: "seconds" },
  "wan/v2.6/image-to-image": { price: 0.03, unit: "images" },
  "wan/v2.6/image-to-video": { price: 0.1, unit: "seconds" },
  "wan/v2.6/image-to-video/flash": { price: 0.05, unit: "seconds" },
  "wan/v2.6/text-to-image": { price: 0.03, unit: "images" },
  "xai/grok-imagine-image": { price: 0.02, unit: "images" },
  "xai/grok-imagine-image/edit": { price: 0.02, unit: "images" },
  "xai/grok-imagine-image/quality/edit": { price: 0.01, unit: "units" },
  "xai/grok-imagine-image/quality/text-to-image": { price: 0.01, unit: "units" },
  "xai/grok-imagine-image/v2.0/edit": { price: 0.01, unit: "units" },
  "xai/grok-imagine-image/v2.0/text-to-image": { price: 0.01, unit: "units" },
  "xai/grok-imagine-video/image-to-video": { price: 0.05, unit: "seconds" },
  "xai/grok-imagine-video/reference-to-video": { price: 0.05, unit: "seconds" },
  "xai/grok-imagine-video/text-to-video": { price: 0.05, unit: "seconds" },
  "xai/grok-imagine-video/v1.5/image-to-video": { price: 0.01, unit: "seconds" },
  "xai/grok-imagine-video/v1.5/reference-to-video": { price: 0.01, unit: "seconds" },
  "xai/grok-imagine-video/v1.5/text-to-video": { price: 0.01, unit: "seconds" },
};

/** Endpoints whose price could not be read on the last run. */
export const FAL_UNPRICED: string[] = [
  "wan/v2.6/text-to-video",
  "fal-ai/invisible-watermark",
  "fal-ai/hunyuan-video-img2vid-lora"
];
